export interface PDFConfig {
  pageSize: "A4" | "letter";
  orientation: "portrait" | "landscape";
  margins: {
    top: number;
    right: number;
    bottom: number;
    left: number;
  };
  fonts: {
    regular: string;
    bold: string;
    amharic: string;
  };
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    text: string;
    lightText: string;
    border: string;
    background: string;
  };
  header: {
    showLogo: boolean;
    logoWidth: number;
    titleEn: string;
    titleAm: string;
    subtitleEn: string;
    subtitleAm: string;
    fontSize: number;
    subFontSize: number;
  };
  footer: {
    showTimestamp: boolean;
    showPageNumbers: boolean;
    text: string;
    fontSize: number;
  };
  stamp: {
    show: boolean;
    text: string;
    textAm: string;
    fontSize: number;
    color: string;
    opacity: number;
  };
  watermark: {
    show: boolean;
    text: string;
    fontSize: number;
    color: string;
    opacity: number;
  };
}

export const pdfConfig: PDFConfig = {
  pageSize: "A4",
  orientation: "portrait",
  margins: {
    top: 25,
    right: 20,
    bottom: 25,
    left: 20,
  },
  fonts: {
    regular: "Helvetica",
    bold: "Helvetica-Bold",
    amharic: "NotoSansEthiopic",
  },
  colors: {
    primary: "#009A44",
    secondary: "#FEDD00",
    accent: "#EF3340",
    text: "#1a1a1a",
    lightText: "#666666",
    border: "#cccccc",
    background: "#ffffff",
  },
  header: {
    showLogo: true,
    logoWidth: 60,
    titleEn: "Federal Democratic Republic of Ethiopia",
    titleAm: "የኢትዮጵያ ፌደራላዊ ዲሞክራሲያዊ ሪፐብሊክ",
    subtitleEn: "Amhara Region - Awi Zone - Dangila Woreda Administration",
    subtitleAm: "የአማራ ክልል - አዊ ዞን - የዳንግላ ወረዳ አስተዳደር",
    fontSize: 14,
    subFontSize: 11,
  },
  footer: {
    showTimestamp: true,
    showPageNumbers: true,
    text: "Generated by Dangila Digital Woreda Services",
    fontSize: 8,
  },
  stamp: {
    show: true,
    text: "OFFICIAL STAMP",
    textAm: "ኦፊሴላዊ ማህተም",
    fontSize: 12,
    color: "#cc0000",
    opacity: 0.7,
  },
  watermark: {
    show: true,
    text: "DANGILA WOREDA",
    fontSize: 60,
    color: "#009A44",
    opacity: 0.03,
  },
};

export const receiptConfig: Partial<PDFConfig> = {
  orientation: "portrait",
  header: {
    ...pdfConfig.header,
    titleEn: "Application Receipt",
    titleAm: "የማመልከቻ ደረሰኝ",
    fontSize: 16,
  },
};

export const certificateConfig: Partial<PDFConfig> = {
  orientation: "landscape",
  header: {
    ...pdfConfig.header,
    titleEn: "Certificate of Approval",
    titleAm: "የማጽደቅ ሰርተፍኬት",
    fontSize: 20,
  },
  stamp: {
    ...pdfConfig.stamp,
    fontSize: 16,
    opacity: 0.8,
  },
};
